//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReport
    {
        public int ReportID { get; set; }
        public System.DateTime Date { get; set; }
        public string Project { get; set; }
        public int Hours { get; set; }
        public int EmployeeID { get; set; }
        public string Employee { get; set; }
        public string Position { get; set; }
    }
}
